# - id: 
#   type: paper
#   description: Sample paper description
#   date: 2023-5-4
#   image: images/research-image
  # buttons:
  #   - type: manubot
  #     link: https://greenelab.github.io/meta-review/
  #   - type: source
  #     text: Manuscript Source
  #     link: https://github.com/greenelab/meta-review
  #   - type: website
  #     link: http://manubot.org/
  # tags:
  #   - artificial intelligence
  #   - machine learning
  #   - NLP
  # repo: greenelab/meta-review
